#ifndef MOVEMENT_DIRECTION_H_INCLUDED
#define MOVEMENT_DIRECTION_H_INCLUDED

enum MovementDirection
{
	STOP_MOVING = 0x00,
	MOVE_FORWARD = 0x05,
	MOVE_BACKWARD = 0x0A,
	ROTATE_RIGHT = 0x06,
	ROTATE_LEFT = 0x09
};

#endif // MOVEMENT_DIRECTION_H_INCLUDED